### PR TITLE
Added Conditions journal

### PR DESCRIPTION
**Pull request by Taroc0**
First part for #11 
Added a 'Conditions' journal to the packs/journals folder, containing pages for each condition available in Draw Steel. I thought a separate journal would keep the system journals organised.

Please let me know if this works for you. I'll wait for your feedback before I proceeding.

### CODE REVIEW

**Comment by JPMeehan** [comment]
Yeah, this makes sense to me. Are these all level 1? Maybe should have the first "Conditions" be level 1 and then the following be level 2. Then, the CONFIG object can point to the UUIDs of each of these journals.

**Comment by Taroc0** [comment]
I'm not sure what you mean by level 1 and level 2. I added a journal called "Conditions". That's on the same level as the other journals (Backer Packet and System Info). The journal "Conditions" consists of ten pages. The first page is a general description of conditions in Draw Steel. The following nine pages are describing one condition at a time. (See screenshot below) All pages are on the same level and I don't know a way to put pages to level 2. The only way to have them at different levels would be to put them on one page and use something like Heading 1 and Heading 2. But that makes referencing them a lot harder, I think.

I afraid I didn't got your point. Sorry.

That's how it looks at the moment:
image

**Comment by JPMeehan** [comment]
When you edit the page, in the top right there's a Level property. You can also see it in the json for the individual pages, it's a top level property.

**Comment by JPMeehan** [comment]
anyways the actual thing I want to see here is the UUID pointers in CONFIG

**Review by JPMeehan — APPROVED** [review]

**Pull request merged**
