### PR TITLE
Add characteristic to damage

### LINKED ISSUE #97: Add Characteristic to ability damage
Follow up to #92 to use the selected characteristic in the damage formula

### PR DESCRIPTION
**Pull request by cdverrett94**
Closes #97 

Let me know if you have a better name for the property or the label.

### CODE REVIEW

**Comment by JPMeehan** [comment]
So, from a philosophical perspective, shouldn't we just have something like `@mod` available in the roll data that people can use to dynamically reference the characteristic?

**Comment by cdverrett94** [comment]
So instead of adding the characteristic to the damage formula in data prep, are you suggesting that by adding @mod to the item's roll data, you could just input the damage formula as like "3 + @mod"?

**Comment by JPMeehan** [comment]
> So instead of adding the characteristic to the damage formula in data prep, are you suggesting that by adding `@mod` to the item's roll data, you could just input the damage formula as like "3 + `@mod`"?

Yeah exactly, makes things more clear. I'd probably name it `@chr` upon consideration, but same basic idea. 

I was going to PR the use ability stuff soon, need to refactor the roll data generally so stuff like the subtype model has a chance to make adjustments beyond simply being included as a shallow copy

**Comment by cdverrett94** [comment]
That's probably fair and less code to maintain. If you're already going to be refactoring the roll data stuff soon, then probably not beneficial for me to add this to the roll data right now. I can just close this one instead.

**Pull request closed without merging**
